-- =====================================================
-- 003. 첫 관리자(또는 신규 사용자) 추가 가이드
-- =====================================================
-- 로컬 개발: pgAdmin에서 boarddb 선택 후 Query Tool에서 실행
-- 배포 시: Neon SQL Editor에서 동일하게 실행
--
-- 회원가입 기능이 차단된 환경(Phase 2.5 이후)에서 새 사용자를 추가하는 절차.
-- 테이블 변경 없음. 실제로 사람을 추가할 때만 INSERT 부분 실행.
--
-- 절차:
-- ----
-- 1) 로컬 머신에서 비밀번호의 bcrypt 해시를 생성합니다.
--    프로젝트 루트에서 PowerShell이나 cmd로 (Node 필요):
--
--      node -e "console.log(require('bcryptjs').hashSync('실제비밀번호', 10))"
--
--    출력 예시:
--      $2b$10$ARm0XaP7K9j8r2u4Hf6S3eK1qZ9o0L....
--
--    saltRounds=10 은 게시판/출고시스템에서 사용 중인 값과 동일합니다.
--
-- 2) 아래 INSERT 문에 위 해시값과 username, nickname을 채워 실행합니다.
--    username은 로그인 시 입력하는 아이디, nickname은 화면에 표시되는 이름입니다.
--
-- 3) 사용자에게 본인 비밀번호를 안전한 채널로 전달하고,
--    가능하면 첫 로그인 후 비밀번호를 변경하도록 안내합니다.
--    (비밀번호 변경 기능은 향후 추가 예정. lib/password-policy.ts 의
--     validatePassword() 가 이미 준비되어 있어 그대로 재사용하면 됩니다.)
-- =====================================================

-- 샘플 INSERT (주석 해제 후 값 채워서 실행)
-- INSERT INTO users (username, password, nickname)
-- VALUES (
--   'admin',                              -- 아이디 (영문/숫자, 3~20자)
--   '$2b$10$여기에_위에서_생성한_해시',     -- bcrypt 해시
--   '관리자'                              -- 닉네임 (화면 표시 이름)
-- );

-- 현재 등록된 사용자 확인용
-- SELECT id, username, nickname, created_at FROM users ORDER BY id;
